// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpAsi-D4rqLGi6xD4dSbrQpMYgAjPLJU4',
    appId: '1:117664216135:web:b498e93cc78cd97004ed62',
    messagingSenderId: '117664216135',
    projectId: 'test1234-6572d',
    authDomain: 'test1234-6572d.firebaseapp.com',
    databaseURL: 'https://test1234-6572d-default-rtdb.firebaseio.com',
    storageBucket: 'test1234-6572d.appspot.com',
    measurementId: 'G-26JL7HFPZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6jc99-1N4OIN8_vXwqTD9jeNUK9yVGr4',
    appId: '1:117664216135:android:8336769c84e4d4b304ed62',
    messagingSenderId: '117664216135',
    projectId: 'test1234-6572d',
    databaseURL: 'https://test1234-6572d-default-rtdb.firebaseio.com',
    storageBucket: 'test1234-6572d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH647QMbo53EWFjUaSPZc2FdNL05XZN0s',
    appId: '1:117664216135:ios:183809a909d9c88e04ed62',
    messagingSenderId: '117664216135',
    projectId: 'test1234-6572d',
    databaseURL: 'https://test1234-6572d-default-rtdb.firebaseio.com',
    storageBucket: 'test1234-6572d.appspot.com',
    iosBundleId: 'com.example.calendarSchedulerFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH647QMbo53EWFjUaSPZc2FdNL05XZN0s',
    appId: '1:117664216135:ios:e1aefc4e7a931f5504ed62',
    messagingSenderId: '117664216135',
    projectId: 'test1234-6572d',
    databaseURL: 'https://test1234-6572d-default-rtdb.firebaseio.com',
    storageBucket: 'test1234-6572d.appspot.com',
    iosBundleId: 'com.example.calendarSchedulerFirebase.RunnerTests',
  );
}
